### PR TITLE
fix(build): Sets correct LIBCCP_VERSION

### LINKED ISSUE #598: .deb Package invalid on Debian
**Describe the bug**
The current .deb release 2.0.0 does not work on debian.

```
 sudo dpkg -i dashboardopcuaclient_2.0.0-rc8-1-g99c30a3_amd64.deb
dpkg: Fehler beim Bearbeiten des Archivs dashboardopcuaclient_2.0.0-rc8-1-g99c30a3_amd64.deb (--install):
 Parsen der Datei »/var/lib/dpkg/tmp.ci/control«, nahe Zeile 2:
 Feld »Depends«, Referenz auf »libstdc++6«: Version »10.3.0/«: ungültiges Zeichen in Versionsnummer
Fehler traten auf beim Bearbeiten von:
 dashboardopcuaclient_2.0.0-rc8-1-g99c30a3_amd64.deb
```

```
/DEBIAN$ cat control
Architecture: amd64
Depends: libstdc++6 (>= 10.3.0/), openssl(>= 1.1.1), ca-certificates
Description: OPC UA client based on open62541 to subscribe to servers implementing umati endorsed companion specification and publish via MQTT to the demo dashboard https://umati.app
Maintainer: Marc Fischer
Package: dashboardopcuaclient
Priority: optional
Section: devel
Version: 2.0.0-rc8-1-g99c30a3
Installed-Size: 46167

```

**Environment:**

- OS: Debian 12
- OPC UA Dashboard Client Version 2.0.0

### PR DESCRIPTION
**Pull request by GoetzGoerisch**

### CODE REVIEW

**Comment by GoetzGoerisch** [comment]
@marcfir @ccvca above fixes #598 but sets libstdc++6 to 13.1.0 as this is the latest on action-runners but not available on a standard ubuntu-22.04 installation.

https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2204-Readme.md#language-and-runtime

How to set a specific installed version in the CI?

**Comment by marcfir** [comment]
Yes this is due to the assumption that the used versions in the runner are available in the official apt repository.

One possibility is a configuration file somewhere. But this means manual adaption.

**Comment by ccvca** [comment]
Can this build be done in a Docker-Container?

**Comment by marcfir** [comment]
This should be possible. Good idea.

**Comment by GoetzGoerisch** [comment]
@marcfir  @ccvca should we merge this fix with the downgrade in the CI  or wait till this happens: https://github.com/actions/runner-images/issues/9679

**Review by marcfir — APPROVED** [review]
lgtm

**Pull request merged**
