### PR TITLE
feat(cmake): add version message of dashboard-client

### LINKED ISSUE #355: Integrate Client Version in Code
We need a way to identify which version of the client is running:

- Schema for version (Commit will not work because of rebasing etc.)
- Tag:Branch:Commit (https://stackoverflow.com/a/7261049)

### PR DESCRIPTION
**Pull request by Kantiran91**
close #355 and #356 if ready 

follow the same structure as open62541

### CODE REVIEW

**Comment by Kantiran91** [comment]
@ccvca We need  the version from git also here:
https://github.com/umati/Dashboard-OPCUA-Client/blob/ac94d0ac4d66bc114d1909c6ad07b5006eefd1c2/.github/CMakeLists.txt#L119

Do you have an idea how to solve this?
Idea 1: execute the SetGitBasedVersion a second time
Idea 2: move the SetGitBasedVersion to the .github cmake project

What do you think?

**Comment by ccvca** [comment]
https://cmake.org/cmake/help/latest/command/string.html#regex-specification
Subgroup matches should simplyfy the parsing of the version string a lot.

See also:
https://cmake.org/cmake/help/latest/variable/CMAKE_MATCH_n.html#variable:CMAKE_MATCH_%3Cn%3E

**Comment by Kantiran91** [comment]
feature is implemented. feature for deb package must be changed.

**Review by GoetzGoerisch — APPROVED** [review]

**Comment by GoetzGoerisch** [comment]
Didn't Check the MQTT part yet.

**Comment by GoetzGoerisch** [comment]
Please set v2.0.0-rc3 initially.

**Comment by Kantiran91** [comment]
@marcfir Do you know why the CI not work here:
https://github.com/umati/Dashboard-OPCUA-Client/actions/runs/4607116144/jobs/8141234890#step:3:3307

**Comment by marcfir** [comment]
@Kantiran91 You have to execute [build.yml:35](https://github.com/umati/Dashboard-OPCUA-Client/blob/056cd301d0de57490f15692234a0172fd7510aee/.github/workflows/build.yml#L35) at the right place. See [here](https://gitlab.kitware.com/cmake/community/-/wikis/doc/cpack/PackageGenerators) and [here](https://gitlab.kitware.com/cmake/community/-/wikis/doc/cpack/Configuration)

**Comment by GoetzGoerisch** [comment]
@Kantiran91 rebased and force pushed

**Pull request merged**
