### PR TITLE
Fix connect with Sign&Encrypt to OPC UA Server

### LINKED ISSUE #353: Connection with Sign&Encrypt not possible
Connection to sample servers are not possible with Sign&Encrypt

### PR DESCRIPTION
**Pull request by marcfir**
Fixes #353.
 * Fixed configuration issue for bypassing certificate verification.
 * Added CMake build type to github actions CMake file.

### CODE REVIEW

**Comment by GoetzGoerisch** [comment]
Doesn't work for me.

LOG:
[2023-04-04 14:53:36.028 (UTC+0200)] warn/client        skip verifying ApplicationURI for the SecurityPolicy http://opcfoundation.org/UA/SecurityPolicy#None
[2023-04-04 14:53:36.028 (UTC+0200)] error/userland     Empty comparing subjectURI and applicationURI
[2023-04-04 14:53:36.028 (UTC+0200)] warn/client        The configured ApplicationURI does not match the URI specified in the certificate for the SecurityPolicy http://opcfoundation.org/UA/SecurityPolicy#Basic128Rsa15
[2023-04-04 14:53:36.028 (UTC+0200)] error/userland     Empty comparing subjectURI and applicationURI
[2023-04-04 14:53:36.028 (UTC+0200)] warn/client        The configured ApplicationURI does not match the URI specified in the certificate for the SecurityPolicy http://opcfoundation.org/UA/SecurityPolicy#Basic256
[2023-04-04 14:53:36.028 (UTC+0200)] error/userland     Empty comparing subjectURI and applicationURI
[2023-04-04 14:53:36.028 (UTC+0200)] warn/client        The configured ApplicationURI does not match the URI specified in the certificate for the SecurityPolicy http://opcfoundation.org/UA/SecurityPolicy#Basic256Sha256
[2023-04-04 14:53:36.028 (UTC+0200)] error/userland     Empty comparing subjectURI and applicationURI
[2023-04-04 14:53:36.028 (UTC+0200)] warn/client        The configured ApplicationURI does not match the URI specified in the certificate for the SecurityPolicy http://opcfoundation.org/UA/SecurityPolicy#Aes128_Sha256_RsaOaep
[2023-04-04 14:53:36.029 (UTC+0200)] info/securitypolicy        The Basic128Rsa15 security policy channel with openssl is created.
[2023-04-04 14:53:36.032 (UTC+0200)] info/network       TCP 7   | New connection to "opcua.umati.app" on port 4840
2023-04-04 14:53:36,033 [DashboardOpcUaClient] INFO void Umati::OpcUa::stateCallback(UA_Client*, UA_SecureChannelState, UA_SessionState, UA_StatusCode):43 Client is connecting
2023-04-04 14:53:36,033 [DashboardOpcUaClient] INFO void Umati::OpcUa::stateCallback(UA_Client*, UA_SecureChannelState, UA_SessionState, UA_StatusCode):76 Session disconnected
2023-04-04 14:53:36,053 [DashboardOpcUaClient] INFO void Umati::OpcUa::stateCallback(UA_Client*, UA_SecureChannelState, UA_SessionState, UA_StatusCode):49 Client hello sent
2023-04-04 14:53:36,053 [DashboardOpcUaClient] INFO void Umati::OpcUa::stateCallback(UA_Client*, UA_SecureChannelState, UA_SessionState, UA_StatusCode):76 Session disconnected
2023-04-04 14:53:36,127 [DashboardOpcUaClient] INFO void Umati::OpcUa::stateCallback(UA_Client*, UA_SecureChannelState, UA_SessionState, UA_StatusCode):61 Client open sent
2023-04-04 14:53:36,127 [DashboardOpcUaClient] INFO void Umati::OpcUa::stateCallback(UA_Client*, UA_SecureChannelState, UA_SessionState, UA_StatusCode):76 Session disconnected
[2023-04-04 14:53:36.163 (UTC+0200)] error/client       Processing the message returned the error code BadCertificateUntrusted
[2023-04-04 14:53:36.163 (UTC+0200)] info/securitypolicy        The Basic128Rsa15 security policy channel with openssl is deleted.
[2023-04-04 14:53:36.163 (UTC+0200)] info/channel       TCP 0   | SC 0  | Closed the SecureChannel
[2023-04-04 14:53:36.163 (UTC+0200)] info/client        Client Status: ChannelState: Closed, SessionState: Closed, ConnectStatus: BadCertificateUntrusted
2023-04-04 14:53:36,163 [DashboardOpcUaClient] INFO void Umati::OpcUa::stateCallback(UA_Client*, UA_SecureChannelState, UA_SessionState, UA_StatusCode):37 The client is disconnected
2023-04-04 14:53:36,164 [DashboardOpcUaClient] INFO void Umati::OpcUa::stateCallback(UA_Client*, UA_SecureChannelState, UA_SessionState, UA_StatusCode):76 Session disconnected
[2023-04-04 14:53:36.164 (UTC+0200)] info/network       TCP 7   | Socket closed
2023-04-04 14:53:36,164 [DashboardOpcUaClient] ERROR bool Umati::OpcUa::OpcUaClient::connect():155 Connecting failed in OPC UA Data Client: BadCertificateUntrusted

2023-04-04 14:53:36,164 [DashboardOpcUaClient] ERROR void Umati::OpcUa::OpcUaClient::connectionStatusChanged(UA_Int32, UA_ServerState):444 Disconnected.

**Comment by marcfir** [comment]
The config must contain the following:
```json
 "OpcUa": {
    "Endpoint": "<URL>",
    "Security": 3,
    "ByPassCertVerification": true
  },
```

**Review by GoetzGoerisch — APPROVED** [review]
Please extend the documentation.

Thank you!

**Review by ccvca — APPROVED** [review]

**Review by GoetzGoerisch — CHANGES_REQUESTED** [review]
Please extend documentation and rebase.

**Comment by marcfir** [comment]
Add documentation for `"ByPassCertVerification": true` to _doc/Configuration.md_

**Review by GoetzGoerisch — APPROVED** [review]

**Pull request merged**
