### PR TITLE
WIP: Customtypes2 for OPC UA 1.04 (Type Dict)

### PR DESCRIPTION
**Pull request by wlkrm**

### CODE REVIEW

**Comment by GoetzGoerisch** [comment]
@wlkrm is this something we can get merged?

**Comment by wlkrm** [comment]
No, I suggested @karstenroethig to finish the PR, to avoid manual integration of custom datatypes in the future. Currently I have no time to finish it.

**Comment by wlkrm** [comment]
I just remembered the issue: the data hub is providing the wrong namespace index via the TypeDictionary. It should be working fine with e.g. the SampleServer. Implementation based on Data typeDefinition should still be added, as TypeDictionary is deprecated in 1.05

**Comment by Kantiran91** [comment]
@wlkrm @GoetzGoerisch  Should we switch to customtypes2-rebased for this feature?

**Comment by GoetzGoerisch** [comment]
I don't recall in what context the -rebase branch was created. I would you with this branch.
But need to resolve the merge conflicts.

**Comment by mdornaus** [comment]
Created new branch Type Dictionary with some fixes. Basically tested with Fluid sample server.

**Comment by mdornaus** [comment]
This pull-request is proceeded in the TypeDictionary branch. Please Merge from there.

**Pull request closed without merging**
