### PR TITLE
feat(core): add case distraction for extendedobject encoding

### LINKED ISSUE #462: umati Client crashes when connecting to opcua.umati.app:4843/node-opcua server
Seems there is an empty nodeId in the types

```
2023-05-11 12:06:54,382 [DashboardOpcUaClient] ERROR void __thiscall Umati::OpcUa::Converter::UaDataValueToJsonValue::setValueFromScalarVariant(UA_Variant &,class nlohmann::json_abi_v3_11_2::basic_json<class std::map,class std::vector,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,bool,__int64,unsigned __int64,double,class std::allocator,struct nlohmann::json_abi_v3_11_2::adl_serializer,class std::vector<unsigned char,class std::allocator<unsigned char> >,void> *,bool):258 Unknow conversion from OpcUaType_ExtensionObject with DataTypeEncodingType: ns=0; i=0
2023-05-11 12:06:54,383 [DashboardOpcUaClient] ERROR void __thiscall Umati::OpcUa::Converter::UaDataValueToJsonValue::setValueFromScalarVariant(UA_Variant &,class nlohmann::json_abi_v3_11_2::basic_json<class std::map,class std::vector,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,bool,__int64,unsigned __int64,double,class std::allocator,struct nlohmann::json_abi_v3_11_2::adl_serializer,class std::vector<unsigned char,class std::allocator<unsigned char> >,void> *,bool):266 The erroc originates from ns=21; s=55240
[2023-05-11 12:06:54.383 (UTC+0200)] error/eventloop    Cannot run EventLoop from the run method itself
[2023-05-11 12:06:54.384 (UTC+0200)] error/eventloop    Cannot run EventLoop from the run method itself
Segmentation fault
```

### PR DESCRIPTION
**Pull request by Kantiran91**
The PR fix #462

### CODE REVIEW

**Comment by Kantiran91** [comment]
@GoetzGoerisch Can you please test the fix?

**Comment by Kantiran91** [comment]
after my test the Client run on mac but not in the docker container. The other version I cloud not test

**Comment by Kantiran91** [comment]
@mdornaus Can you test this on linux?

**Comment by GoetzGoerisch** [comment]
@Kantiran91 rebased, working on `ubuntu-22.04`

**Comment by GoetzGoerisch** [comment]
@Kantiran91 remaining errors:

```
dashboard-opcua-client-opcua_client-1  | 2023-05-26 07:25:00,159 [DashboardOpcUaClient] INFO virtual void Umati::OpcUa::OpcUaClient::readTypeDictionaries():369 Unable to resolve DataType:http://opcfoundation.org/UA/MachineVision2/ SEMI_E10SystemStateDataType
dashboard-opcua-client-opcua_client-1  | 2023-05-26 07:25:00,160 [DashboardOpcUaClient] INFO virtual void Umati::OpcUa::OpcUaClient::readTypeDictionaries():369 Unable to resolve DataType:http://opcfoundation.org/UA/MachineVision2/ SEMI_E10SystemStateInfoDataType
```

**Comment by GoetzGoerisch** [comment]
I ran tests for containers with `alpine` and ´debian-bullseye-slim` which show the same error.

After building the type map, the client wants to subscribe to the typedefinitons and not the instances and then crashes.

```
2023-05-26 10:02:32,918 [DashboardOpcUaClient] INFO void Umati::Dashboard::OpcUaTypeReader::readTypes():63 Browsing object types finished
2023-05-26 10:02:32,959 [DashboardOpcUaClient] INFO bool Umati::MachineObserver::MachineObserver::canBrowseMachineList(std::__cxx11::list<ModelOpcUa::BrowseResult_t>&):129 Searching for machines
2023-05-26 10:02:33,263 [DashboardOpcUaClient] INFO std::__cxx11::list<ModelOpcUa::BrowseResult_t> Umati::MachineObserver::MachineObserver::browseForMachines(ModelOpcUa::NodeId_t, ModelOpcUa::NodeId_t, std::function<bool(ModelOpcUa::NodeId_t)>):224 IdentificationType not found, probably because namespace nsu=http://opcfoundation.org/UA/MachineTool/;i=13 is not in the config, or this type does not have an identification type.
2023-05-26 10:02:33,498 [DashboardOpcUaClient] INFO std::__cxx11::list<ModelOpcUa::BrowseResult_t> Umati::MachineObserver::MachineObserver::browseForMachines(ModelOpcUa::NodeId_t, ModelOpcUa::NodeId_t, std::function<bool(ModelOpcUa::NodeId_t)>):224 IdentificationType not found, probably because namespace nsu=http://opcfoundation.org/UA/Robotics/;i=1002 is not in the config, or this type does not have an identification type.
2023-05-26 10:02:33,640 [DashboardOpcUaClient] INFO std::__cxx11::list<ModelOpcUa::BrowseResult_t> Umati::MachineObserver::MachineObserver::browseForMachines(ModelOpcUa::NodeId_t, ModelOpcUa::NodeId_t, std::function<bool(ModelOpcUa::NodeId_t)>):224 IdentificationType not found, probably because namespace nsu=http://opcfoundation.org/UA/Robotics/;i=1003 is not in the config, or this type does not have an identification type.
2023-05-26 10:02:33,786 [DashboardOpcUaClient] INFO std::__cxx11::list<ModelOpcUa::BrowseResult_t> Umati::MachineObserver::MachineObserver::browseForMachines(ModelOpcUa::NodeId_t, ModelOpcUa::NodeId_t, std::function<bool(ModelOpcUa::NodeId_t)>):224 IdentificationType not found, probably because namespace nsu=http://opcfoundation.org/UA/Robotics/;i=1004 is not in the config, or this type does not have an identification type.
2023-05-26 10:02:37,231 [DashboardOpcUaClient] INFO std::__cxx11::list<ModelOpcUa::BrowseResult_t> Umati::MachineObserver::MachineObserver::browseForMachines(ModelOpcUa::NodeId_t, ModelOpcUa::NodeId_t, std::function<bool(ModelOpcUa::NodeId_t)>):224 IdentificationType not found, probably because namespace nsu=http://opcfoundation.org/UA/PlasticsRubber/Extrusion_v2/Cutter/;i=1005 is not in the config, or this type does not have an identification type.
2023-05-26 10:02:37,691 [DashboardOpcUaClient] INFO std::__cxx11::list<ModelOpcUa::BrowseResult_t> Umati::MachineObserver::MachineObserver::browseForMachines(ModelOpcUa::NodeId_t, ModelOpcUa::NodeId_t, std::function<bool(ModelOpcUa::NodeId_t)>):224 IdentificationType not found, probably because namespace nsu=http://opcfoundation.org/UA/MachineVision/AMCM/;i=1008 is not in the config, or this type does not have an identification type.
2023-05-26 10:02:38,175 [DashboardOpcUaClient] INFO std::__cxx11::list<ModelOpcUa::BrowseResult_t> Umati::MachineObserver::MachineObserver::browseForMachines(ModelOpcUa::NodeId_t, ModelOpcUa::NodeId_t, std::function<bool(ModelOpcUa::NodeId_t)>):224 IdentificationType not found, probably because namespace nsu=http://opcfoundation.org/UA/MachineTool/;i=13 is not in the config, or this type does not have an identification type.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

**Review by GoetzGoerisch — CHANGES_REQUESTED** [review]
We need to find the reason for the runtime crash before we should merge this.

**Comment by Kantiran91** [comment]
@mdornaus Can you please have a look to the issue ?

**Comment by Kantiran91** [comment]
the new commit helps also detecting issues like #471

**Review by GoetzGoerisch — APPROVED** [review]

**Pull request merged**
